name: Validate Setup

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check test scripts
      run: |
        npm run test:unit --if-present
        npm run test:integration --if-present

    - name: Test package can be packed
      run: |
        npm pack --dry-run
